@City_Bus_Management_System_HostAddress = https://localhost:44382



###

GET {{City_Bus_Management_System_HostAddress}}/admin

###

GET {{City_Bus_Management_System_HostAddress}}/route

###

@tripId=1
GET {{City_Bus_Management_System_HostAddress}}/route/RouteForTrip/{{tripId}}

###
